### ISSUE TITLE
Running InstaRelinker Infinite loading wheel

### ISSUE THREAD

**Issue by uxrobui** [telerik/figma-instarelinker-community#2]
Stuck on "Running InstaRelinker" state. Waited the entire weekend, still no progress. 

I have tried to run the plugin on both the browser based platform and the Microsoft app with the same problem.

What troubleshooting can I do to fix the problem?

**Comment by atanasovg** [comment]
Hello,

Not sure what is causing this unexpected behavior, it most likely a bug. Some questions to help me better understand the case:

* When the plugin spins forever is the rest of the document/UI responsive or blocked?
* What is the toast information by the plugin? It prompts for every operation it starts.
* Could you check for exceptions in the Figma development console? You can open the console by clicking the Plugins-Development->Open Console command in the menu of the desktop version of Figma.

Also, it would help a lot if you can isolate the behavior in a demo Figma file so that I can reproduce and debug locally.

Thanks

**Comment by uxrobui** [comment]
So to answer some of the points.
________________________________________

_When the plugin spins forever is the rest of the document/UI responsive or blocked?_
 - When the plugin spins forever the document is responsive, however the document is not responsive in the first step of running the plugin, detailed below.
________________________________________

_What is the toast information by the plugin? It prompts for every operation it starts._

- The toast information when running the plugin appears as follows:

1. finding remote components and styles in the selection. this might take a while, please wait.... (document is unresponsive during this step)
2. (Some step that happened to quick to note down)
3. generating styles preview
4. Running InstaRelinker (forever)
________________________________________

_Could you check for exceptions in the Figma development console? You can open the console by clicking the Plugins-Development->Open Console command in the menu of the desktop version of Figma._

- I cannot see any exceptions in the Dev Con but there are 4 warnings shown. Those warnings are as followed
1. Origin trial controlled feature not enabled: 'display-capture'.
2. unhandled promise rejection: Error: in set_textAutoResize: Cannot write to node with unloaded font "Inter Regular". Please call figma.loadFontAsync({ family: "Inter", style: "Regular" }) and await the returned promise first.
3. at buildTextStylesPreview (PLUGIN_7_SOURCE:1065)
4. (no warning title)
________________________________________

Here is a link to the figma file, im trying to relink the components in the "Import for InstaRelink" page.

**Comment by atanasovg** [comment]
Thanks, this is a bug and I will try to isolate and fix it. Once we are ready, we will upload a new version of the plugin.

Thanks for reporting, will post here when a new version is published.

**Comment by uxrobui** [comment]
No problem, seems like a promising plugin. Looking forward to the fix! 

Thanks for being so responsive.

**Comment by ivancucer** [comment]
@atanasovg any ideas when the fix will be available? 👨🏻‍🦳

**Comment by ivancucer** [comment]
Looks like the freshly released version 1.2 has been fixed. Thank you @atanasovg

**Comment by atanasovg** [comment]
Welcome @ivancucer :) 
@uxrobui - a new version has been published

Please give it a try and let me know if everything works as expected.

**Comment by uxrobui** [comment]
@atanasovg works as expected. Great work and thanks again :)
