### ISSUE TITLE
Plugin doesn't work if an instance has a color style applied

### ISSUE THREAD

**Issue by ivancucer** [telerik/figma-instarelinker-community#3]
Hi @atanasovg 

I've found a critical bug. Please take a look at this screencast https://cln.sh/UMZzqY

Any ideas?

Thanks!

**Comment by atanasovg** [comment]
Hi @ivancucer,

Thank you for reporting this. The scenario works on my machine with the current development version and I guess that there is some fix that happened during the iterative commits in the codebase. I will examine more thoroughly and will fix this in the released version. Will let you know when new version is published.

Thanks

**Comment by atanasovg** [comment]
@ivancucer A new version is just uploaded, please give it a try and let us know how it goes.

**Comment by ivancucer** [comment]
Everything seems to be working as expected 👍 Thank you @atanasovg
